name: deployment

on: pull_request

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: check if user changed its own file
      if: github.event.pull_request.merged == false
      run: |
          URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
          FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
          echo $FILES == "${{ github.actor }}.json"
          if [ "$FILES" = "${{ github.actor }}.json" ]; then
            echo "${{ github.actor }} has changed his own file!!"
          else
            echo "${{ github.actor }} has not changed his own file!!"
            exit 1
          fi  
    - name: automatic merge
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        comment: "Accepted."
